# Generated by Django 3.2.20 on 2023-08-21 18:54

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, unique=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('post_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.TextField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_posts', to=settings.AUTH_USER_MODEL)),
                ('down_vote', models.ManyToManyField(blank=True, related_name='post_down_votes', to=settings.AUTH_USER_MODEL)),
                ('super_vote', models.ManyToManyField(blank=True, related_name='post_super_votes', to=settings.AUTH_USER_MODEL)),
                ('up_vote', models.ManyToManyField(blank=True, related_name='post_up_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('comment_body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='home.userposts')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
