# Generated by Django 3.2.20 on 2023-08-21 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userPSrofiles',
            new_name='userProfiles',
        ),
    ]
