# Generated by Django 3.2.20 on 2023-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_userpsrofiles_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
