# Generated by Django 3.2.20 on 2023-09-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofiles_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='username',
        ),
    ]
